server:
  port: 8890


spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/eladmin
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

p6spy:
  config:
    append: com.p6spy.engine.spy.appender.Slf4JLogger
    logMessageFormat: com.p6spy.engine.spy.appender.CustomLineFormat
    customLogMessageFormat: executionTime:%(executionTime)| 执行sql:%(sqlSingleLine)

